---------
-- CUSTOMER AGREEGATED DATA
---------

CREATE OR REPLACE VIEW RFM_SEGMENTED_DATA AS
WITH CUSTOMER_AGREEGATED_DATA AS
(SELECT `Customer Name`, 
datediff( (SELECT MAX(`Order Date`) FROM sales), MAX(`Order Date`) ) AS RECENCY_VALUE,
COUNT(DISTINCT `Order ID`) AS FREQUENCY_VALUE,
round(SUM(`Sales`)) AS MONYTARY_VALUE
FROM sales
GROUP BY `Customer Name`),

-- ----------
-- SEGEMENT CUSTOMER
-- ----------
RFM_SCORE AS(
SELECT c.*,
NTILE(4) OVER (ORDER BY RECENCY_VALUE DESC) AS R_SCORE,
NTILE(4) OVER (ORDER BY FREQUENCY_VALUE ASC) AS F_SCORE,
NTILE(4) OVER (ORDER BY MONYTARY_VALUE ASC) AS M_SCORE
FROM CUSTOMER_AGREEGATED_DATA AS C)

SELECT
`Customer Name`,
R.RECENCY_VALUE,
R.R_SCORE,
R.FREQUENCY_VALUE,
R.F_SCORE,
R.MONYTARY_VALUE,
R.M_SCORE,
(R_SCORE + F_SCORE + M_SCORE) AS TOTAL_SCORE,
CONCAT_WS('',R_SCORE, F_SCORE, M_SCORE) AS RFM_SCORE_COMBINATION
FROM RFM_SCORE AS R;


-- --------------
-- RFM_ANALYSIS
-- --------------
CREATE OR REPLACE VIEW RFM_ANALYSIS AS
SELECT * ,
CASE
	WHEN RFM_SCORE_COMBINATION IN (111, 112, 121, 132, 211, 212, 114, 141) THEN 'CHURNED CUSTOMER'
    WHEN RFM_SCORE_COMBINATION IN (113, 134, 143, 24, 334, 343, 344, 144) THEN 'SLIPPING AWAY, CONNOT LOSE'
    WHEN RFM_SCORE_COMBINATION IN (311, 411, 331) THEN 'NEW CUSTOMER'
    WHEN RFM_SCORE_COMBINATION IN (222, 231, 221, 223, 233, 322) THEN 'POTENTIAL CUSTOMER'
    WHEN RFM_SCORE_COMBINATION IN (323, 333, 321, 341, 422, 332, 432) THEN 'ACTIVE CUSTOMER'
    WHEN RFM_SCORE_COMBINATION IN (433, 434, 443, 444) THEN 'LOYAL'
ELSE 'CANNOT BE DEFINED'
END AS CUSTOMER_SEGMENT
FROM RFM_SEGMENTED_DATA;

SELECT
	CUSTOMER_SEGMENT,
    COUNT(*) AS NUMBER_OF_CUSTOMER
FROM rfm_analysis
GROUP BY CUSTOMER_SEGMENT;